steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ambient-cubist-393519/github.com/kojomensahonums/summariser-app:$COMMIT_SHA', '--build-arg HF_TOKEN=$$_HF_TOKEN', '.']
    secretEnv: ['HF_TOKEN']
availableSecrets:
  secretManager:
    - versionName: projects/269347135162/secrets/HF_TOKEN/versions/1
      env: 'HF_TOKEN'
images:
  - 'gcr.io/ambient-cubist-393519/github.com/kojomensahonums/summariser-app:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

